# 🐼 Bloc 2 — Pandas : Premiers Pas

**Objectifs de ce bloc :**
- Comprendre les structures Series et DataFrame.
- Charger et lire des données depuis des fichiers CSV.
- Explorer rapidement un dataset (aperçu, infos, statistiques).
- Sélectionner et filtrer des données avec `.loc` et `.iloc`.

In [5]:
import numpy as np
import pandas as pd

## 1. De NumPy à Pandas

NumPy est rapide mais limité pour l'analyse de données d'entreprise : types homogènes, pas de noms de colonnes explicites, pas d'index alphanumériques.

**Pandas = NumPy + index nommés + différents data types + outils robustes**

## 2. Series et DataFrame

Un **DataFrame** est un tableau à deux dimensions. Chaque colonne d'un dataframe est une **Series** (un tableau 1D avec un index).

In [6]:
# Création d'une Series
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(f"Series: {s}")

Series: a    10
b    20
c    30
dtype: int64

In [7]:
# convertissons cette Serie en dataframe
df = pd.DataFrame(s)
df

# Que constatez vous?

    0
a  10
b  20
c  30

In [8]:
# Définition d'un dictionnaire d'example
data = {
    'nom': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'salaire': [35000, 42000, 50000]
}
# Création d'un DataFrame depuis un dictionnaire
df_dict = pd.DataFrame(data)

display(df_dict)   

# Vérifions le data type
print(type(df_dict))

# on doit trouver ceci: <class 'pandas.DataFrame'>

       nom  age  salaire
0    Alice   25    35000
1      Bob   30    42000
2  Charlie   35    50000

<class 'pandas.DataFrame'>

In [9]:
# dans notebook, annoncer la variable suffit pour afficher le dataframe
df_dict

       nom  age  salaire
0    Alice   25    35000
1      Bob   30    42000
2  Charlie   35    50000

## 3. Charger un jeu de données existants

Pandas brille par ses outils d'entrée/sortie.
Une fois les données chargées, on utilise le **triptyque d'exploration** : `.head()`, `.info()`, `.describe()`.

## Exercice: Recherche documentation 

- cherchez les différents type de fichiers que pandas peut lire
- en citer 3 de votre choix
- appliquer la

In [10]:
# Charger un dataset -> changer pour la bonne fonction
#products = pd."FONCTION_ICI"('../01_data/raw/thelook_products.csv')

In [11]:
# Charger un dataset -> changer pour la bonne fonction
products = pd.read_csv('../01_data/raw/thelook_products.csv')

### 3.1 EDA: Exploratory Data Analysis
La première étape, après avoir chargé un fichier est de toujours observer et s'approprier le dataset auquel on est confronté.
Voici les fonctions essentielles qui vous permettront de réaliser cela:

In [12]:
# Explorer les premières lignes
head = products.head()
head

,id,name,category,brand,department,cost,retail_price,sku,distribution_center_id
0,1,Tommy Hilfiger Regular Fit Underwear,Underwear,Tommy Hilfiger,Women,6.57,10.31,SKU-00001,5
1,2,Hurley Pro Shorts,Shorts,Hurley,Women,20.85,37.55,SKU-00002,6
2,3,Columbia Sport Tops & Tees,Tops & Tees,Columbia,Men,21.34,44.52,SKU-00003,9
3,4,Volcom Classic Leggings,Leggings,Volcom,Women,14.98,42.24,SKU-00004,2
4,5,Hurley Urban Outerwear & Coats,Outerwear & Coats,Hurley,Women,89.58,149.11,SKU-00005,5

In [13]:
# Informations sur les types et valeurs manquantes
infos = products.info()
infos

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2000 non-null   int64
 1   name                    2000 non-null   str
 2   category                2000 non-null   str
 3   brand                   2000 non-null   str
 4   department              2000 non-null   str
 5   cost                    2000 non-null   float64
 6   retail_price            2000 non-null   float64
 7   sku                     2000 non-null   str
 8   distribution_center_id  2000 non-null   int64
dtypes: float64(2), int64(2), str(5)
memory usage: 140.8 KB

Prenez le temps d'observer les types de données. Cette méthode nous donne beaucoup de metadata

**Questions:** combien de type différents observez-vous dans ce jeu de donnée?

In [8]:
# Statistiques descriptives sur les colonnes numériques
stats = products.describe()
round(stats)     # on utilise round() pour arrondir et avoir plus de clarté

           id    cost  retail_price  distribution_center_id
count  2000.0  2000.0        2000.0                  2000.0
mean   1000.0    34.0          77.0                     6.0
std     577.0    32.0          75.0                     3.0
min       1.0     1.0           3.0                     1.0
25%     501.0    14.0          31.0                     3.0
50%    1000.0    25.0          56.0                     6.0
75%    1500.0    41.0          93.0                     8.0
max    2000.0   198.0         512.0                    10.0

In [14]:
# Distribution des catégories (regarder la structure du jeu de données obtenu, grâce à info())
categories = products['category'].value_counts()

# Que va faire cette fonction selon vous ?
# categories

In [15]:
# complétez en affichant que les 5 premières lignes

top_five = categories
top_five

category
Jumpsuits & Rompers              130
Pants                            118
Shorts                           109
Fashion Hoodies & Sweatshirts    109
Sweaters                         109
Blazers & Jackets                108
Accessories                      107
Leggings                         105
Dresses                          105
Outerwear & Coats                104
Suits & Sport Coats              104
Jeans                            103
Swim                             101
Skirts                           101
Active                           101
Sleep & Lounge                    99
Socks & Hosiery                   97
Underwear                         95
Tops & Tees                       95
Name: count, dtype: int64

## 4. Sélection avec .loc et .iloc

- `.loc[lignes, colonnes]` : Sélection basée sur les **labels** (les noms des index et colonnes).
- `.iloc[lignes, colonnes]` : Sélection basée sur la **position** entière (comme dans NumPy).

In [16]:
# .iloc (position)
print("Première ligne, deux premières colonnes (iloc) :")
display(products.iloc[0, :2])

Première ligne, deux premières colonnes (iloc) :

id                                         1
name    Tommy Hilfiger Regular Fit Underwear
Name: 0, dtype: object

In [17]:
# Sélection conditionnelle (très courant)
mask = products['retail_price'] > 100
produits_chers = products[mask]
print(f"\nNombre de produits à plus de 100€ : {len(produits_chers)}")

Nombre de produits à plus de 100€ : 452

### RAPPEL: Quelle est la différence entre = et == dans Python?

In [18]:
# Multiples conditions avec & (ET) et | (OU)
# Les parenthèses sont obligatoires ! 
jeans_chers = products[(products['category'] == 'Jeans') & (products['retail_price'] > 50)]

# ici nous avons pu filtrer avec une double conditions:
print(f"Nombre de jeans à plus de 50€ : {len(jeans_chers)}")

Nombre de jeans à plus de 50€ : 88

# Exercices pratiques

# `Exercice 2.1 — Découverte du dataset: TheLook

**Instructions :**
Chargez `../01_data/raw/thelook_products.csv`.
1. Combien y a-t-il de produits ? Quelles sont les colonnes disponibles ?
2. Quelles catégories existent ? (utilisez `.value_counts()`)
3. Quel est le `retail_price` moyen ?
4. Combien y a-t-il de marques uniques (`nunique()`) ?
5. Y a-t-il des valeurs manquantes dans ce dataset ? (utilisez `.isna().sum()`)

In [36]:
products = pd.read_csv('../01_data/raw/thelook_products.csv')
# nombre de  produits
nb_produits = len(products)
print(f"Nombre total de produits : {nb_produits}")
# colonnes disponibles
colonnes = products.columns
print(f"Colonnes disponibles : {colonnes}")
# categories existantes
categories_existantes = products['category'].unique()
print(f"Catégories existantes : {categories_existantes}")
# retail_price moyen
prix_moyen = products['retail_price'].mean()
print(f"Prix moyen : {prix_moyen:.2f}€")

# nombre de marques uniques
nb_marques_uniques = products['brand'].nunique()
print(f"Nombre de marques uniques : {nb_marques_uniques}")
# valeurs manquantes dans le dataset .isna.sum()
valeurs_manquantes = products.isna().sum()
print(f"Valeurs manquantes par colonne :\n{valeurs_manquantes}")

Nombre total de produits : 2000
Colonnes disponibles : Index(['id', 'name', 'category', 'brand', 'department', 'cost', 'retail_price',
       'sku', 'distribution_center_id'],
      dtype='str')
Catégories existantes : <StringArray>
[                    'Underwear',                        'Shorts',
                   'Tops & Tees',                      'Leggings',
             'Outerwear & Coats',                       'Dresses',
                          'Swim',           'Jumpsuits & Rompers',
 'Fashion Hoodies & Sweatshirts',                'Sleep & Lounge',
                   'Accessories',                         'Pants',
                         'Jeans',               'Socks & Hosiery',
                      'Sweaters',           'Suits & Sport Coats',
                        'Skirts',             'Blazers & Jackets',
                        'Active']
Length: 19, dtype: str
Prix moyen : 77.42€
Nombre de marques uniques : 20
Valeurs manquantes par colonne :
id                        0
name                      0
category                  0
brand                     0
department                0
cost                      0
retail_price              0
sku                       0
distribution_center_id    0
dtype: int64

## Exercice 2.2 — Filtrer

**Instructions :**
Chargez `../01_data/raw/thelook_orders.csv`.
1. Analysez le fichier. Les colonnes temporelles (comme `created_at`) doivent idéalement être parsées en datetime, bien qu'on puisse se contenter de filtrer par string pour l'instant.
2. Filtrez les commandes avec `status == 'Complete'` **ET** `num_of_item > 2`.
3. Combien y a-t-il de commandes correspondant à ces critères ?
4. Extrayez le mois de la colonne `created_at` et trouvez quel mois concentre le plus de ces grosses commandes complétées.

In [30]:

df_chelook_orders = pd.read_csv('../01_data/raw/thelook_orders.csv')
# filtrer les commandes avec le stauts = ='complete' & num_of_items > 2
df_chelook_orders_complete = df_chelook_orders[(df_chelook_orders['status'] == 'complete') & (df_chelook_orders['num_of_items'] > 2)]

KeyError: 'num_of_items'

## Exercice 2.3 — Connaitre les utilisateurs

**Instructions :**
Chargez `../01_data/raw/thelook_users.csv`.
1. Pour chaque source de trafic (`traffic_source`), comptez le nombre d'utilisateurs et calculez la moyenne d'âge.
2. Quelle source de trafic attire les utilisateurs les plus jeunes en moyenne ?
3. Quelle est la répartition globale Hommes/Femmes (`gender`) dans ce dataset ?
4. Quels sont les 10 pays comptant le plus grand nombre d'utilisateurs ?

In [ ]:
# Votre code ici